#spring:
#  datasource:
#    # 数据库驱动
#    driver-class-name: com.mysql.jdbc.Driver
#    # 数据库连接地址
#    url: jdbc:mysql://localhost:3306/springboot-jdbc-integration
#    # 数据库连接用户名
#    username: root
#    # 数据库连接用户密码
#    password: 123456
custom:
  datasource:
    # 数据库驱动
    driver-class-name: com.mysql.jdbc.Driver
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/springboot-jdbc-integration
    # 数据库连接用户名
    username: root
    # 数据库连接用户密码
    password: 123456

custom-second:
  source:
    # 数据库驱动
    driver-class-name: com.mysql.jdbc.Driver
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/springboot-jdbc-integration-2
    # 数据库连接用户名
    username: root
    # 数据库连接用户密码
    password: 123456